2024-12-02 20:52:10,469 | WARNING | Неверный тип данных для объекта Runner
2024-12-02 20:52:10,475 | WARNING | Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject_calculator\test_12_4.py", line 81, in test_run
    runner = Runner(2)
  File "C:\Users\Administrator\PycharmProjects\pythonProject_calculator\test_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-02 20:52:10,481 | WARNING | Неверная скорость для Runner
2024-12-02 20:52:10,482 | WARNING | Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject_calculator\test_12_4.py", line 70, in test_walk
    runner = Runner("Вася", -5)
             ~~~~~~^^^^^^^^^^^^
  File "C:\Users\Administrator\PycharmProjects\pythonProject_calculator\test_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
